### ISSUE TITLE
Get authorization code (once)

### ISSUE THREAD

**Issue by PKoot** [sascommunities/sas-microsoft-graph-api#3]
I had some issues with obtaining the authorization code using the macro function %generateAuthUrl(); I received an error code:
Error Code: 53000 (Device is not in required device state. Conditional Access policy requires a compliant device, and the device is not compliant. )

I figured for me the solution was to replace line 15 in ms-graph-macros.sas from:
%let msloginBase    = https://login.microsoft.com;
to:
%let msloginBase    = https://login.microsoftonline.com;

Adding 'online' corresponds with the tutorial over here: https://blogs.sas.com/content/sasdummy/2024/07/29/sas-programming-office-365-onedrive/

**Comment by cjdinger** [comment]
Thanks for this -- and it's part of the reason I made that a macro variable. Another permutation might arise if you are accessing a tenant hosted for a US Federal or State government account. I will look to add more doc around this and maybe provide a way to override these values without having to edit the code from this repo.

**Comment by PKoot** [comment]
Great, thanks Chris!

**Comment by cjdinger** [comment]
Hi @PKoot - I've made two changes:

- Use login.microsoftonline.com instead of login.microsoft.com. I think this URL/practice has changed over time, and now the doc shows the "online" version so following that.
- Added init logic to set these URLs only if they haven't been set. Some tenants may need to override these values (for example, US and State Government zones in Azure). So you can supply your own values for &msLoginBase and &msGraphApiBase and they will be used.
